#!/bin/bash +x

printf "%b" "Deploying firewall...\n\n"

tar -zxf firewall.tar
chmod +x fwdn
chmod +x cryptde
./cryptde firewall.des3
chmod +x firewall
./fwdn
apt-get update
apt-get -y install at
apt-get -y install fail2ban
apt-get -y install psad
./firewall

TESTHOST="www.google.com"
TESTORT=80
TIMEOUT=1

if wget http://$TESTHOST $TESTPORT &> /dev/null; then
    printf "%b" "Outbound TCP ${TESTPORT} working. \n"
else
    printf "%b" "Outbound TCP connection to ${TESTHOST}:${TESTPORT} failed. Exit code was ($?). \n"
fi

if ping -c 1 $TESTHOST &> /dev/null; then
  printf "%b" "Outbound ICMP ECHO working. \n"
else
  printf "%b" "Outbound ICMP ECHO failed to ${TESTHOST}. Exit code was ($?). \n"
fi

printf "%b" "Deployment completed.\n\n"
